### ISSUE TITLE
The INCLUDE_ZGC macro should be used as a value

### ISSUE THREAD

**Issue by wks** [mmtk/openjdk#7]
In `src/hotspot/share/opto/matcher.cpp`, there is a line `#if defined(INCLUDE_ZGC) && !defined(INCLUDE_THIRD_PARTY_HEAP)`.  Supposedly the code following that should only be enabled when ZGC is enabled.

However, the `INCLUDE_ZGC` macro should not be used by testing if it is defined.  It is always defined (as 0 or 1) and should be used as a boolean value.  Therefore `defined(INCLUDE_ZGC)` is always true.

This is causing compilation error when compiling OpenJDK where neither ZGC nor third-party heap is enabled.  Because OpenJDK 11 only supports ZGC on Linux/x64, attempting to compile this openjdk repo on MacOS or AArch64 without third-party heap will result in compilation error because the code enclosed by this macro is erroneously enabled.  This problem can also be reproduced on Linux/x64 by disabling ZGC manually.

How to reproduce:

On Linux/x86, follow `README.md` in `mmtk-openjdk, but
*   add `--enable-jvm-features=-zgc` to `sh configure`
*   remove `THIRD_PARTY_HEAP=$PWD/../../openjdk` from `make`

Then compilation will fail.

**Comment by qinsoon** [comment]
Thanks for the issue. The PR has been merged. The config option should be `--with-jvm-features=-zgc`, and the PR fixed the build error.
